[package]
name = "soloud"
version = "0.1.0"
authors = ["MoAlyousef <mohammed.alyousef@neurosrg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
soloud-sys = { path = "../soloud-sys", version = "0.1.0" }

[features]
use-ninja = ["soloud-sys/use-ninja"]
